# Generated by Django 2.0.5 on 2018-05-12 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fashion', '0002_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('fashion', 'fashion'), ('beauty', 'beauty'), ('lifestyle', 'lifestyle'), ('travel', 'travel'), ('fitness', 'fitness')], default='fashion', max_length=10),
        ),
    ]
