# Generated by Django 2.0.5 on 2018-05-12 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fashion', '0003_auto_20180512_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
